version: 0.1
log:
  formatter: json
  level: info
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
notifications:
  endpoints:
    - name: jenkins
      url: http://where-ever-you-are-jenkins
    - name: requestbin
      url: http://requestbin:8000/1e0hfql1
